site_name: Documentation for the official sedex-Client Docker Image
site_description: Documentation for the official sedex-Client Docker image.
theme:
  name: material
  language: en
  logo: assets/favicon.png
  features:
    - navigation.top
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      toc_depth: 3
nav:
  - 'Documentation Home': index.md
  - 'Client V6 (current)':
      - 'Basic Usage': v6/index.md
      - 'Advanced Docker Options': v6/advanced-docker-options.md
      - 'Advanced sedex Client Config': v6/sedex-client-configuration-options.md
      - 'sedex Web Service Proxy': v6/sedex-webservice-proxy.md
      - 'Kubernetes & Co.': v6/orchestration.md
  - 'Client V5 (deprecated)':
      - 'Usage': v5/index.md
  - 'Client V6 (new)':
      - 'Introduction': v6n/introduction.md
      - 'The sedex system':
         - 'System Overview': v6n/sedex-system/overview_sedex.md
         - 'sedex-Client': v6n/sedex-system/sedex-client.md
      - 'Basic Concepts of the Container Image': v6n/basic-concepts.md
      - 'Requirements': v6n/requirements.md
      - 'Initial Configuration' :
        - 'With P12-Certificate': v6n/initial-configuration/initial_configuration_with_certificate.md
        - 'With CRID+OTP': v6n/initial-configuration/initial_configuration_with_crid_and_otp.md
      - 'Start & Stop sedex-Client' :
        - 'with docker': v6n/run/run_with_docker.md
        - 'with docker-compose': v6n/run/run_with_docker-compose.md
        - 'with kubernetes': v6n/run/run_with_kubernetes.md
      - 'Configuration':
          - 'sedex-Client': v6n/configuration/sedex-client-options.md
          - 'sedex Web Service Proxy': v6n/configuration/sedex-web-service-proxy-options.md
          - 'Container' : v6n/configuration/container-options.md
      - 'Observation':
          - 'Accessing Logs': v6n/observation/accessing-logs.md
          - 'Monitoring State': v6n/observation/monitoring-state.md
      - 'Backup your Data': v6n/backup_data.md
      - 'Versions & Changes': v6n/versions_changes.md
      - 'FAQ': v6n/faq.md
  - 'Contact' : contact.md
