site_name: Documentation for the official sedex-Client Docker Image
site_description: Documentation for the official sedex-Client Docker image.
theme:
  name: material
  language: en
  logo: assets/favicon.png
  features:
    - navigation.top
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - toc:
      toc_depth: 3
nav:
  - 'Documentation Home': index.md
  - 'The sedex system':
      - 'sedex System Overview': sedex-system/overview_sedex.md
      - 'sedex Client': sedex-system/sedex-client.md
  - 'Client Container V6 (current)':
      - 'Before Starting': client-container-v6/index.md
      - 'Important Concepts': client-container-v6/important-concepts.md
      - 'Requirements': client-container-v6/requirements.md
      - 'Initial Configuration' :
        - 'With P12-Certificate': client-container-v6/initial-configuration/initial_configuration_with_certificate.md
        - 'With CRID+OTP': client-container-v6/initial-configuration/initial_configuration_with_crid_and_otp.md
      - 'Start & Stop sedex-Client' :
        - 'with docker': client-container-v6/run/run_with_docker.md
        - 'with docker-compose': client-container-v6/run/run_with_docker-compose.md
        - 'with kubernetes': client-container-v6/run/run_with_kubernetes.md
      - 'Configuration':
          - 'sedex-Client': client-container-v6/configuration/sedex-client-options.md
          - 'sedex Web Service Proxy': client-container-v6/configuration/sedex-web-service-proxy-options.md
          - 'Container' : client-container-v6/configuration/container-options.md
      - 'Observation':
          - 'Accessing Logs': client-container-v6/observation/accessing-logs.md
          - 'Monitoring State': client-container-v6/observation/monitoring-state.md
      - 'Backup your Data': client-container-v6/backup_data.md
      - 'Versions & Changes': client-container-v6/versions_changes.md
      - 'FAQ': client-container-v6/faq.md
  - 'Client Container V5 (old)':
      - 'Usage': client-container-v5/index.md
  - 'Contact' : contact.md
